server:
  port: 8080
  servlet:
    context-path: /xt-demo

spring:
  application:
    name: xt-demo
  mvc:
    pathmatch:
      # springboot集成Swagger2报错
      # Springboot2.6以后将SpringMVC默认路径匹配策略从AntPathMatcher更改为PathPatternParser，导致出错
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  profiles:
    active: ${DEPLOYMODE:dev}
  jackson:
    time-zone: GMT+8
  # 数据库配置
  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      minimum-idle: 4
      maximum-pool-size: 20

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      field-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  httpclient:
    connection-timeout: 3000

# eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8011/eureka/
  instance:
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/${spring.application.name}/swagger-ui.html



#方式2：负载均衡配置文件
#指定使用Nacos提供的负载均衡策略（优先调用同一集群实例，基于随机和权重）
#service-stock:
#  ribbon:
#    #NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.

pagehelper:
  helper-dialect: mysql
  page-size-zero: true
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# 日志配置文件路径
logging:
  config: classpath:logback.xml

